version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: spring-mybatis-test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root1234